### ISSUE TITLE
Fail in Documentation build

### ISSUE THREAD

**Issue by CharlesGaydon** [IGNF/myria3d#56]
There seem to be an issue in documentation build, due to an invalid environment creation (pyg issue https://github.com/pyg-team/pytorch_geometric/issues/2040). I'll look into it.

_Originally posted by @CharlesGaydon in https://github.com/IGNF/myria3d/issues/53#issuecomment-1400514730_

**Comment by CharlesGaydon** [comment]
> WARNING: autodoc: failed to import module 'train' from module 'myria3d'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/work/myria3d/myria3d/myria3d/train.py", line 22, in <module>
    from myria3d.models.model import Model
  File "/home/runner/work/myria3d/myria3d/myria3d/models/model.py", line 6, in <module>
    from torch_geometric.data import Batch
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/site-packages/torch_sparse/__init__.py", line 19, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/site-packages/torch/_ops.py", line 220, in load_library
    ctypes.CDLL(path)
  File "/usr/share/miniconda3/envs/myria3d/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory
